platform :ios, '7.0'

pod 'DateTools'
pod 'SDWebImage', '~>3.7'
pod 'XLForm', '~> 3.0'
pod 'AFNetworking'
pod 'CocoaLumberjack'
pod 'IQKeyboardManager'
pod 'MBProgressHUD'
pod 'BlocksKit'
pod 'pop','~> 1.0'
pod 'SWTableViewCell', '~> 0.3.7'
pod 'MJRefresh'
pod 'MJExtension'
pod 'YTKNetwork'
pod 'Masonry'
pod 'FMDB'
pod 'Colours'
pod 'FCFileManager'